format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$fill\
[](fg:#1d2230)\
$status\
$cmd_duration\
[](fg:#394260 bg:#1d2230)\
$battery\
[](fg:#769ff0 bg:#394260)\
$memory_usage\
[](fg:#a3aed2 bg:#769ff0)\
$time\
[▓▒░](#a3aed2)\
\n$character"""

[fill]
symbol = ' '

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[cmd_duration]
min_time = 500
format = '[$duration ](fg:#769ff0 bg:#1d2230)'

[status]
style = 'fg:#a3aed2 bg:#1d2230'
symbol = '󰅙  '
success_symbol = '  ' 
format = '[$symbol]($style)'
map_symbol = true
disabled = false

[battery]
disabled = false
full_symbol	= '󰁹'
charging_symbol	= '󱟠'
discharging_symbol = '󱟞'
unknown_symbol	= '󰁽'
empty_symbol = '󱃍'
format = '[$symbol$percentage ]($style)'

[[battery.display]]
threshold = 100
style = "bg:#394260"

[memory_usage]
disabled = false
threshold = -1
format = '[ $ram_pct ]($style)'
style = "fg:#e3e5e5 bg:#769ff0"


[time]
disabled = false
time_format = '%R'
style = "bg:#1d2230"
format = '[[  $time ](fg:#090c0c bg:#a3aed2)]($style)'

