format = """
[](#2e3440)\
$os\
[](fg:#2e3440 bg:#3b4252)\
[ 󰉋 ](fg:#5e81ac bg:#3b4252)$directory\
[](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#4c566a)\
$status\
[](#4c566a)$sudo\
$fill\
[](#4c566a)\
[  ](fg:#8fbcbb bg:#4C566A)$cmd_duration\
[](fg:#434c5e bg:#4c566a)\
$battery\
[](fg:#3b4252 bg:#434c5e)\
[ ](fg:#81a1c1 bg:#3b4252)$memory_usage\
[](fg:#2e3440 bg:#3b4252)\
[ ](fg:#5e81ac bg:#2e3440)$time\
[](#2e3440)\
\n$character"""

[os]
disabled = false
format = '[$symbol](#2e3440)'

[os.symbols]
Alpaquita = "[  ](fg:#5e81ac bg:#2e3440)"
Alpine = "[  ](fg:#5e81ac bg:#2e3440)"
AlmaLinux = "[  ](fg:#5e81ac bg:#2e3440)"
Amazon = "[  ](fg:#5e81ac bg:#2e3440)"
Android = "[   ](fg:#5e81ac bg:#2e3440)"
Arch = "[  ](fg:#5e81ac bg:#2e3440)"
Artix = "[  ](fg:#5e81ac bg:#2e3440)"
CentOS = "[  ](fg:#5e81ac bg:#2e3440)"
Debian = "[  ](fg:#5e81ac bg:#2e3440)"
DragonFly = "[  ](fg:#5e81ac bg:#2e3440)"
Emscripten = "[   ](fg:#5e81ac bg:#2e3440)"
EndeavourOS = "[   ](fg:#5e81ac bg:#2e3440)"
Fedora = "[  ](fg:#5e81ac bg:#2e3440)"
FreeBSD = "[  ](fg:#5e81ac bg:#2e3440)"
Garuda = "[ 󰛓 ](fg:#5e81ac bg:#2e3440)"
Gentoo = "[  ](fg:#5e81ac bg:#2e3440)"
HardenedBSD = "[ 󰞌 ](fg:#5e81ac bg:#2e3440)"
Illumos = "[ 󰈸 ](fg:#5e81ac bg:#2e3440)"
Kali = "[   ](fg:#5e81ac bg:#2e3440)"
Linux = "[  ](fg:#5e81ac bg:#2e3440)"
Mabox = "[  ](fg:#5e81ac bg:#2e3440)"
Macos = "[  ](fg:#5e81ac bg:#2e3440)"
Manjaro = "[  ](fg:#5e81ac bg:#2e3440)"
Mariner = "[   ](fg:#5e81ac bg:#2e3440)"
MidnightBSD = "[ ](fg:#5e81ac bg:#2e3440)"
Mint = "[   ](fg:#5e81ac bg:#2e3440)"
NetBSD = "[  ](fg:#5e81ac bg:#2e3440)"
NixOS = "[  ](fg:#5e81ac bg:#2e3440)"
OpenBSD = "[ 󰈺 ](fg:#5e81ac bg:#2e3440)"
openSUSE = "[   ](fg:#5e81ac bg:#2e3440)"
OracleLinux = "[ 󰌷 ](fg:#5e81ac bg:#2e3440)"
Pop = "[   ](fg:#5e81ac bg:#2e3440)"
Raspbian = "[  ](fg:#5e81ac bg:#2e3440)"
Redhat = "[   ](fg:#5e81ac bg:#2e3440)"
RedHatEnterprise = "[   ](fg:#5e81ac bg:#2e3440)"
RockyLinux = "[   ](fg:#5e81ac bg:#2e3440)"
Redox = "[ 󰀘 ](fg:#5e81ac bg:#2e3440)"
Solus = "[ 󰠳 ](fg:#5e81ac bg:#2e3440)"
SUSE = "[   ](fg:#5e81ac bg:#2e3440)"
Ubuntu = "[  ](fg:#5e81ac bg:#2e3440)"
Unknown = "[  ](fg:#5e81ac bg:#2e3440)"
Void = "[  ]((fg:#5e81ac bg:#2e3440)"
Windows = "[ 󰍲 ](fg:#5e81ac bg:#2e3440)"

[directory]
truncation_length = 1
read_only = '[ ](fg:#5e81ac bg:#3b4252)'
format = "[$path$read_only](fg:#d8dee9 bg:#3b4252)"

[git_branch]
symbol = '[ ](fg:#81a1c1 bg:#434c5e)'
format = '[[ $symbol$branch](fg:#d8dee9 bg:#434c5e)](fg:#434c5e)'

[git_status]
format = '[[($all_status$ahead_behind)](fg:#d8dee9 bg:#434c5e)](fg:#434c5e)'

[status]
symbol = '[󰅙 ](fg:#bf616a bg:#4c566a)'
success_symbol = '[ ](fg:#a3be8c bg:#4c566a)'
not_executable_symbol = '[ ](fg:#d08770 bg:#4c566a)'
not_found_symbol = '[ ](fg:#ebcb8b bg:#4c566a)'
sigint_symbol = '[󰿅 ](fg:#a3be8c bg:#4c566a)'
format = '[$symbol](#4c566a)'
map_symbol = true
disabled = false

[sudo]
symbol = '[SUDO](fg:#d8dee9 bg:#bf616a)'
disabled = false
format = '[ $symbol](#bf616a)'

[fill]
symbol = ' '

[cmd_duration]
min_time = 0
format = '[$duration](fg:#d8dee9 bg:#4C566A)'


[battery]
disabled = false
full_symbol	= '[󰁹](fg:#81a1c1 bg:#4C566A)'
charging_symbol	= '[󱟠](fg:#a3be8c bg:#4C566A)'
discharging_symbol = '[󱟞](fg:#ebcb8b bg:#4C566A)'
unknown_symbol	= '[󰁽](fg:#b48ead bg:#4C566A)'
empty_symbol = '[󱃍](fg:#bf616a bg:#4C566A)'
format = '[$symbol$percentage](fg:#d8dee9 bg:#434c5e)'

[[battery.display]]
threshold = 50

[memory_usage]
disabled = false
threshold = -1
format = '[$ram_pct](fg:#d8dee9 bg:#3b4252)'

[time]
disabled = false
time_format = '%R'
format = '[[$time](fg:#d8dee9 bg:#2e3440)](bg:#2e3440)'

[character]
success_symbol = '[ 󰄾 ](fg:#a3be8c bg:#2e3440)'
error_symbol = '[ 󰄾 ](fg:#bf616a bg:#2e3440)'
vimcmd_symbol = '[ 󰄼 ](fg:#5e81ac bg:#2e3440)'
format = '[$symbol](#2e3440)'
