format = """
[](#5e81ac)\
$os\
[](fg:#5e81ac bg:#88c0d0)\
$directory\
[](fg:#88c0d0 bg:#81a1c1)\
$git_branch\
$git_status\
[](fg:#81a1c1 bg:#8fbcbb)\
$status\
[](#8fbcbb)\
$fill\
[](fg:#8fbcbb)\
[  ](fg:#eceff4 bg:#8fbcbb)$cmd_duration\
[](fg:#81a1c1 bg:#8fbcbb)\
$battery\
[](fg:#88c0d0 bg:#81a1c1)\
$memory_usage\
[](fg:#5e81ac bg:#88c0d0)\
$time\
[](#5e81ac)\
\n$character"""
[os]
disabled = false
format = '[ $symbol](fg:#eceff4 bg:#5e81ac)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[directory]
format = "[ 󰉋 $path](fg:#eceff4 bg:#88c0d0)"
truncation_length = 3
truncation_symbol = "…/"

[cmd_duration]
min_time = 1
format = '[$duration](fg:#eceff4 bg:#8fbcbb)'

[git_branch]
format = '[[ $symbol$branch](fg:#eceff4 bg:#81a1c1 )](fg:#81a1c1 )'

[git_status]
format = '[[($all_status$ahead_behind)](fg:#eceff4 bg:#81a1c1 )](fg:#81a1c1 )'

[fill]
symbol = ' '

[status]
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = ''
not_found_symbol = ''
sigint_symbol = ''
format = '[ $symbol ](fg:#eceff4 bg:#8fbcbb)'
map_symbol = true
disabled = false

[battery]
disabled = false
full_symbol	= '󰁹'
charging_symbol	= '󱟠'
discharging_symbol = '󱟞'
unknown_symbol	= '󰁽'
empty_symbol = '󱃍'
format = '[$symbol$percentage](fg:#eceff4 bg:#88c0d0)'

[[battery.display]]
threshold = 50

[memory_usage]
disabled = false
threshold = -1
format = '[ $ram_pct](fg:#eceff4  bg:#88c0d0)'

[time]
disabled = false
time_format = '%R'
format = '[[ $time](fg:#eceff4 bg:#5e81ac)](bg:#5e81ac)'

[character]
success_symbol = '[ 󱞪 ](fg:#eceff4 bg:#5e81ac)'
error_symbol = '[ 󱞪 ](fg:#eceff4 bg:#5e81ac)'
format = '[$symbol](#5e81ac)'
