format = """
[░▒▓](#a3aed2)\
$os(bg:#a3aed2 fg:#090c0c)\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
[  ](fg:#e3e5e5 bg:#394260)$cmd_duration\
[](fg:#394260 bg:#1d2230)\
$git_branch\
$git_status\
[](fg:#1d2230)\
$fill\
[](fg:#1d2230)\
$status\
[](fg:#394260 bg:#1d2230)\
$battery\
[](fg:#769ff0 bg:#394260)\
$memory_usage\
[](fg:#a3aed2 bg:#769ff0)\
$time\
[▓▒░](#a3aed2)\
\n$character"""

[os]
disabled = false
format = '[ $symbol](bg:#a3aed2 fg:#090c0c)'

[directory]
format = "[ $path](fg:#e3e5e5 bg:#769ff0)"
truncation_length = 3
truncation_symbol = "…/"

[cmd_duration]
min_time = 1
format = '[$duration](fg:#e3e5e5 bg:#394260)'

[git_branch]
format = '[[ $symbol$branch](fg:#e3e5e5 bg:#1d2230)](fgi:#1d2230)'

[git_status]
format = '[[($all_status$ahead_behind)](fg:#e3e5e5 bg:#1d2230)](fg:#1d2230)'

[fill]
symbol = ' '

[status]
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = ''
not_found_symbol = ''
sigint_symbol = ''
format = '[$symbol ](fg:#a3aed2 bg:#1d2230)'
map_symbol = true
disabled = false

[battery]
disabled = false
full_symbol	= '󰁹'
charging_symbol	= '󱟠'
discharging_symbol = '󱟞'
unknown_symbol	= '󰁽'
empty_symbol = '󱃍'
format = '[$symbol$percentage](bg:#394260)'

[[battery.display]]
threshold = 100

[memory_usage]
disabled = false
threshold = -1
format = '[ $ram_pct](fg:#e3e5e5 bg:#769ff0)'

[time]
disabled = false
time_format = '%R'
format = '[[ $time](fg:#090c0c bg:#a3aed2)](bg:#1d2230)'

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'
